////////


#cmakedefine01 INCLUDE__EXPRJLIBAPP

#if (INCLUDE__EXPRJLIBAPP == 1)

#cmakedefine01 EXPRJLIBAPP__EXCLUDE_MYMULTIPLY
#cmakedefine01 EXPRJLIBAPP__EXCLUDE_MYDIVIDE

#endif /* (INCLUDE__EXPRJLIBAPP == 1) */


